apiVersion: v1
kind: Service
metadata:
  name: cpo-mqtt-service 
  labels:
    app: nodered
spec:
  type: NodePort
  ports:
  - name: mosquitto
    port: 1883
  - name: mosquitto-web
    port: 80
    targetPort: 9001
  selector:
    app: nodered
